# Generated by Django 5.2.8 on 2025-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sequence', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Invoice Sequence',
                'verbose_name_plural': 'Global Invoice Sequences',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
                ('custom_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the invoice item', null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('scheduled', 'Scheduled'), ('custom', 'Custom')], default='scheduled', max_length=50)),
                ('partner_status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('scheduled', 'Scheduled'), ('custom', 'Custom')], default='scheduled', max_length=50)),
                ('custom_status', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('auto', models.BooleanField(default=False, help_text='Whether the invoice was auto-generated from project costs.')),
                ('amc_year', models.IntegerField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, help_text="Automatically set when status changes to 'paid', cleared when status changes from 'paid'", null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_percentages', models.JSONField(blank=True, default=dict, help_text='JSON field to store cost percentages for software, customization, and integration')),
            ],
            options={
                'ordering': ['due_date', 'invoice_no'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('type', models.CharField(choices=[('local', 'Local'), ('overseas', 'Overseas')], max_length=10)),
                ('info', models.TextField(blank=True, null=True)),
                ('software_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customization_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('integration_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('local', 'Local'), ('overseas', 'Overseas')], default='local', max_length=10)),
                ('currency', models.CharField(choices=[('PKR', 'PKR'), ('USD', 'USD')], default='PKR', max_length=3)),
                ('custom_costs', models.JSONField(blank=True, default=list)),
                ('referrer_software_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referrer_customization_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referrer_integration_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referrer_amc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amc_start_date', models.DateField(blank=True, help_text='Start date for AMC calculations', null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
