# Generated by Django 5.2.8 on 2025-11-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalInvoiceSequence',
        ),
        migrations.RemoveField(
            model_name='project',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='amc_cost',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='customization_cost',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='integration_cost',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='software_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amc_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='custom_costs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='referrer_amc_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='referrer_customization_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='referrer_integration_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='referrer_software_cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tax_rate',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Referrer',
        ),
    ]
